/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ConstantsInterface extends utils.Interface {
  functions: {
    "getCoordinator()": FunctionFragment;
    "getKeyHash()": FunctionFragment;
    "getSubscriptionId()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getCoordinator"
      | "getKeyHash"
      | "getSubscriptionId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKeyHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionId",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Constants extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConstantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCoordinator(overrides?: CallOverrides): Promise<[string]>;

    getKeyHash(overrides?: CallOverrides): Promise<[string]>;

    getSubscriptionId(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getCoordinator(overrides?: CallOverrides): Promise<string>;

  getKeyHash(overrides?: CallOverrides): Promise<string>;

  getSubscriptionId(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getCoordinator(overrides?: CallOverrides): Promise<string>;

    getKeyHash(overrides?: CallOverrides): Promise<string>;

    getSubscriptionId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getCoordinator(overrides?: CallOverrides): Promise<BigNumber>;

    getKeyHash(overrides?: CallOverrides): Promise<BigNumber>;

    getSubscriptionId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getKeyHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSubscriptionId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
