/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lotterySol from "./Lottery.sol";
export type { lotterySol };
export type { Constants } from "./Constants";
export type { MaticToken } from "./MaticToken";
export type { NoEther } from "./NoEther";
export type { TestArray } from "./TestArray";
export type { USDT } from "./USDT";
export type { VRFCoordinatorV2Mock } from "./VRFCoordinatorV2Mock";
export type { VRFv2SubscriptionConsumer } from "./VRFv2SubscriptionConsumer";
